name: Build iOS app

on:
  push:
    branches:
      - master
    paths:
      - "The Walking Monster/*"
      - "The Walking Monster/*/*"
      - "The Walking Monster/*/*/*"

jobs:
  # ios-lint:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Run Swiftlint and iblint
  #       run: |
  #         "./Pods/SwiftLint/swiftlint"
  #         "./Pods/IBLinter/bin/iblinter"

  ios-build:
    # needs: ios-lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: bundle install
        run: |
          gem install bundler:1.17.3
          bundle install
        env:
          CI: "true"
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v1
        with:
          token: ${{secrets.github_token}}
      - name: build	and beta release
        run: bundle exec fastlane ios beta
        env:
          CI: "true"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GITHUB_PASSWORD: ${{ secrets.GH_PASSWORD }}
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}
          DEVELOPER_DIR: "/Applications/Xcode_11.2.1.app"
